export const ANIMATED_SOURCE = {
  capybara: {
    hibi: {
      staticUrl: '',
      fallbackStaticUrl: '',
      type: 'animation',
      animationUrl: '',

      animatedData: {
        width: 180,
        height: 180,
        numPlays: 4,
        playTime: 1000,
        frames: [
          {
            left: 0,
            top: 0,
            width: 180,
            height: 180,
            delay: 100,
            disposeOp: 1,
            blendOp: 0,
            imageData: {},
            imageElement: null,
          },
          {
            left: 6,
            top: 110,
            width: 172,
            height: 59,
            delay: 100,
            disposeOp: 0,
            blendOp: 0,
            imageData: {},
            imageElement: null,
          },
          {
            left: 11,
            top: 93,
            width: 167,
            height: 75,
            delay: 100,
            disposeOp: 0,
            blendOp: 0,
            imageData: {},
            imageElement: null,
          },
          {
            left: 5,
            top: 74,
            width: 173,
            height: 91,
            delay: 100,
            disposeOp: 1,
            blendOp: 0,
            imageData: {},
            imageElement: null,
          },
          {
            left: 6,
            top: 6,
            width: 169,
            height: 171,
            delay: 100,
            disposeOp: 0,
            blendOp: 0,
            imageData: {},
            imageElement: null,
          },
          {
            left: 7,
            top: 5,
            width: 157,
            height: 155,
            delay: 100,
            disposeOp: 2,
            blendOp: 0,
            imageData: {},
            imageElement: null,
          },
          {
            left: 7,
            top: 83,
            width: 162,
            height: 77,
            delay: 100,
            disposeOp: 2,
            blendOp: 0,
            imageData: {},
            imageElement: null,
          },
          {
            left: 7,
            top: 6,
            width: 157,
            height: 154,
            delay: 100,
            disposeOp: 2,
            blendOp: 0,
            imageData: {},
            imageElement: null,
          },
          {
            left: 0,
            top: 0,
            width: 1,
            height: 1,
            delay: 100,
            disposeOp: 0,
            blendOp: 0,
            imageData: {},
            imageElement: null,
          },
          {
            left: 7,
            top: 6,
            width: 157,
            height: 46,
            delay: 100,
            disposeOp: 0,
            blendOp: 0,
            imageData: {},
            imageElement: null,
          },
        ],
      },
    },
  },
};
